name: ezyride_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Add a version constraint
  shared_preferences: ^2.1.0 # Add a version constraint
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.10+1
  location: ^6.0.2 # Make sure you're using a version that supports background location updates
  provider: ^6.1.2 # This is already correct
  web_socket_channel: ^3.0.1 # Add a version constraint
  google_maps_flutter:
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/images/autorickshaw.svg
    - lib/assets/images/autorickshaw.png
    - lib/assets/images/ezyridelogo.svg
    - lib/assets/images/ezyridelogo.png
  uses-material-design: true
