name: ezyride_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  cupertino_icons:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/images/autorickshaw.svg
    - lib/assets/images/autorickshaw.png
    - lib/assets/images/ezyridelogo.svg
    - lib/assets/images/ezyridelogo.png
  uses-material-design: true
